apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-app-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: java-app
  namespaceSelector:
    matchNames:
      - java-app
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
