
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: java-app
  labels:
    app: java-app
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: LoadBalancer
